# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534096ce745e114708a3bb5695b0033c15891d02f926254166ddbf885b24030c39b6905436e26eae86e4a38206bfba43109b975d906fd2e10d6024ec442cf926

test:
  secret_key_base: 067488e87294855b4d725e843f658ca5403426e6c9a1bd55c6475c634737e352782288675d32d837b71b773c823a6228087d498baa72df2f481cdf0dfc87d61b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
